language: python
matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=lint
    - python: "3.5"
      env: TOXENV=cov
      after_success: coveralls
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
install: pip install -U tox coveralls
script: tox
deploy:
  provider: pypi
  user: andrewsayre
  password:
    secure: OGsIlIb1eCammtMUxF01KZAScLw1iueiQHGJZNnr+8E/9Mfz9mNtBXptr5/pJAAxSYsOW3vaCZrymE4UMDMhMxwoH/vsyBJ0QkZw+kra5TgZdoOLelCcjfskV7N7eJtYRTsIqN7uRlHQ7+GTHn1Z0yCxMPE+nkMZXGgGhQs1b1b9/NSF5soBY6VaXRCEWeTVqATnxUxilnMfvhpk1MNXoLWiHlEL0iSJFhk+NV6cF1eX2zZn9vgjOXlyGHUFx+xipu5ulMeAqQKIFfQ4OLfCyQN+bHHhozjqfczbybAz0pjIhoZ/cByA5kbNQOGxDMWczJzFM1ejj+eEK+4uYOoJoJOTB1wynT2Mk7rrOnydfxg4ou1UMpIWUYxBxBHTe5WFSBerF/9UvXmpZM2etKHqpJo0K1/MX96n/v90nYEqGW/D3H19yp0Jz4R6V8yYsMbwEPA43X2IXCYQGst7ZIhGTlhmNT9+aw69AXAvIBoBOxqQAshAT5F5n/BNaHnkxGKdTfFMtECf/9RWgIBgzwoRiTJ5fx1//xTfM1mIxjoPHaGy0134O7Zux1efnJUDsJWpSW4PrAVdJ19xfJOKMH0sS6IhCggdk5SNzWuhAD0Lmf6SaUF3m5E/0vMDaWf3QTZ9Swh/r4J4/6cREFjTxpEsqwy+PFRXxnqReFAfmAeZjRY=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
    condition: $TOXENV = lint